IF NOT EXISTS (SELECT 1 FROM Sys.Objects WHERE Name = 'Compra')
BEGIN
	CREATE TABLE Compra (
		Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
		Data DATETIME NOT NULL,
		ValorTotal DECIMAL NOT NULL,
		Descricao VARCHAR(500) NULL,
		NotaFiscal VARCHAR(MAX) NULL
	);
END

IF NOT EXISTS (SELECT 1 FROM Sys.Objects WHERE Name = 'Compra')
BEGIN
	CREATE TABLE CompraItem (
		Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL DEFAULT NEWID(),
		Descricao VARCHAR(500) NOT NULL,
		ValorUnitario DECIMAL NOT NULL,
		Quantidade INT NOT NULL,
		DescricaoUnidade VARCHAR(500) NULL,
		IdCompra UNIQUEIDENTIFIER NOT NULL,
		FOREIGN KEY (IdCompra) REFERENCES Compra (Id)
	);
END